
FROM node:lts-alpine as build-stage

# make the 'app' folder the current working directory
WORKDIR /app

COPY ./FE/package*.json /app/

COPY ./FE/ /app/

RUN npm install


RUN npm run build


# production stage
FROM nginx:stable-alpine as production-stage


COPY --from=build-stage /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]